-- LingoDesk learning activity history
-- Run this once in Supabase SQL Editor after the main schema.

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  unit_id integer check (unit_id is null or unit_id > 0),
  activity_type text not null check (
    activity_type in (
      'login',
      'unit_opened',
      'practice_started',
      'practice_completed',
      'dialogue_started',
      'dialogue_completed',
      'progress_updated'
    )
  ),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_activity enable row level security;

drop policy if exists "Users can read their own activity" on public.user_activity;
create policy "Users can read their own activity"
  on public.user_activity for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own activity" on public.user_activity;
create policy "Users can insert their own activity"
  on public.user_activity for insert
  to authenticated
  with check (auth.uid() = user_id);

create index if not exists user_activity_user_created_idx
  on public.user_activity(user_id, created_at desc);

create index if not exists user_activity_unit_idx
  on public.user_activity(unit_id);
