-- Administrator audit log
-- Run this once in Supabase SQL Editor.

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null check (action in (
    'user_created',
    'user_updated',
    'user_enabled',
    'user_disabled',
    'user_password_reset',
    'user_admin_granted',
    'user_admin_revoked',
    'user_deleted'
  )),
  target_username text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log alter column actor_user_id drop not null;

alter table public.admin_audit_log drop constraint if exists admin_audit_log_actor_user_id_fkey;
alter table public.admin_audit_log add constraint admin_audit_log_actor_user_id_fkey foreign key (actor_user_id) references auth.users(id) on delete set null;

alter table public.admin_audit_log enable row level security;
-- No browser policies: only the server-side admin function reads/writes this table.

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log(created_at desc);

create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log(target_username);
